// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace task_manager_api.TaskManager.Data.CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        private ApplicationDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("7cb1de85-afe2-449d-93e5-abcd2c2c010a"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var activityLog = ActivityLogEntityType.Create(this);
            var role = RoleEntityType.Create(this);
            var taskItem = TaskItemEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var userToken = UserTokenEntityType.Create(this);

            ActivityLogEntityType.CreateForeignKey1(activityLog, taskItem);
            ActivityLogEntityType.CreateForeignKey2(activityLog, user);
            TaskItemEntityType.CreateForeignKey1(taskItem, user);
            UserEntityType.CreateForeignKey1(user, role);
            UserTokenEntityType.CreateForeignKey1(userToken, user);

            ActivityLogEntityType.CreateAnnotations(activityLog);
            RoleEntityType.CreateAnnotations(role);
            TaskItemEntityType.CreateAnnotations(taskItem);
            UserEntityType.CreateAnnotations(user);
            UserTokenEntityType.CreateAnnotations(userToken);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
