// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TaskManager.Data;
using task_manager_api.TaskManager.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]
